"""PlotManualDataRisks.py

Simple plotting utility for risk values generated by ManualDataAnalysis.

The script expects a text file with one predicted risk value per line (e.g., produced
by saving ``risk_values`` from ManualDataAnalysis). It reads the file, converts to
floats, and renders a basic histogram and line plot.

Usage:
    python PlotManualDataRisks.py [path/to/predicted_risks.txt]

If no file path is provided, it defaults to `predicted_risks.txt` in the current
working directory.
"""

import sys
import os

import matplotlib.pyplot as plt


def load_risks(path: str) -> list:
    """Read risk values from a plain text file."""
    if not os.path.exists(path):
        raise FileNotFoundError(f"Risk file not found: {path}")
    risks = []
    with open(path, "r") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                risks.append(float(line))
            except ValueError:
                # ignore non-numeric lines
                pass
    return risks


def main():
    filename = sys.argv[1] if len(sys.argv) > 1 else "predicted_risks.txt"
    print(f"Loading risk values from {filename}")
    risks = load_risks(filename)
    # remove any negative values which are invalid
    risks = [r for r in risks if r >= 0]
    if not risks:
        print("No valid (non-negative) risk values found in file.")
        return

    print(f"Loaded {len(risks)} risk values")

    # simple line plot
    plt.figure(figsize=(10, 4))
    plt.plot(risks, marker=".", linestyle="-", alpha=0.7)
    plt.title("Predicted Risk Values")
    plt.xlabel("Sample index")
    plt.ylabel("Risk")
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.show()

    # histogram
    plt.figure(figsize=(6, 4))
    plt.hist(risks, bins=30, color="skyblue", edgecolor="black")
    plt.title("Distribution of Predicted Risks")
    plt.xlabel("Risk")
    plt.ylabel("Frequency")
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
    main()
